<link rel="stylesheet" href="{{asset('assets/front')}}/css/bootstrap.min.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/animate.min.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/magnific-popup.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/fontawesome-all.min.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/odometer.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/jarallax.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/swiper-bundle.min.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/BeerSlider.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/tg-cursor.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/slick.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/default.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/aos.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/style.css">
<link rel="stylesheet" href="{{asset('assets/front')}}/css/responsive.css">