<?php

namespace Database\Seeders;

use App\Models\DashboardMemberProfile;
use Illuminate\Database\Seeder;

class DashboardMemberProfileSeeder extends Seeder
{
    public function run(): void
    {
        $asset = static fn (string $path): string => 'assets/dashboard/gn-central/preview-assets/'.$path;
        $directoryOverrides = [
            'africa-dyslexia-organization' => [
                'directory_card_title' => 'Africa Dyslexia Organization, Ghana',
                'directory_location' => 'Ghana',
                'directory_address' => 'Ghana',
                'directory_description' => 'A pan-African nonprofit advancing early identification, structured literacy, and inclusive education across the continent.',
                'directory_image_path' => '/assets/directory/ghana-logo.png',
                'region_code' => 'GH',
                'latitude' => 5.6037,
                'longitude' => -0.1870,
                'map_zoom' => 5,
                'highlight_radius' => 250000,
            ],
            'australian-dyslexia-association' => [
                'directory_location' => 'Australia',
                'directory_address' => 'Australia',
                'directory_description' => 'An Australian not-for-profit association supporting people and families affected by dyslexia through advocacy and evidence-based support.',
                'directory_image_path' => '/assets/directory/australian-dyslexia-association-logo.png',
                'region_code' => 'AU',
                'latitude' => -35.2809,
                'longitude' => 149.1300,
                'map_zoom' => 4,
                'highlight_radius' => 450000,
            ],
            'bellavista-school' => [
                'directory_card_title' => 'Bellavista S.H.A.R.E., South Africa',
                'directory_location' => 'Johannesburg, South Africa',
                'directory_address' => 'Johannesburg, South Africa',
                'directory_description' => 'Bellavista S.H.A.R.E. extends Bellavista School\'s remedial and professional-learning work across South Africa and beyond.',
                'directory_image_path' => '/assets/directory/south-africa-logo.png',
                'region_code' => 'ZA',
                'latitude' => -26.2041,
                'longitude' => 28.0473,
                'map_zoom' => 5,
                'highlight_radius' => 320000,
            ],
            'dyslexia-and-social-support-services-botswana' => [
                'directory_card_title' => 'Botswana Dyslexia Association',
                'directory_location' => 'Botswana',
                'directory_address' => 'Botswana',
                'directory_description' => 'A nonprofit trust in Botswana providing advocacy, counselling, assessments, and after-school remedial support.',
                'directory_image_path' => '/assets/directory/botswana-logo.png',
                'region_code' => 'BW',
                'latitude' => -24.6282,
                'longitude' => 25.9231,
                'map_zoom' => 5,
                'highlight_radius' => 260000,
            ],
            'dyslexia-ireland' => [
                'directory_location' => 'Ireland',
                'directory_address' => 'Ireland',
                'directory_description' => 'Ireland\'s national representative body for dyslexia and dyscalculia, providing assessment, tuition, training, and advocacy.',
                'directory_image_path' => '/assets/directory/ireland-logo.png',
                'region_code' => 'IE',
                'latitude' => 53.3498,
                'longitude' => -6.2603,
                'map_zoom' => 5,
                'highlight_radius' => 220000,
            ],
            'dyslexia-association-of-indonesia' => [
                'directory_location' => 'Indonesia',
                'directory_address' => 'Indonesia',
                'region_code' => 'ID',
                'latitude' => -6.2088,
                'longitude' => 106.8456,
                'map_zoom' => 5,
                'highlight_radius' => 450000,
            ],
            'dyslexia-science' => [
                'directory_location' => 'Scotland',
                'directory_address' => 'Scotland',
                'region_code' => 'GB',
                'latitude' => 55.9533,
                'longitude' => -3.1883,
                'map_zoom' => 5,
                'highlight_radius' => 220000,
            ],
            'fana-ethiopia' => [
                'directory_location' => 'Addis Ababa, Ethiopia',
                'directory_address' => 'Addis Ababa, Ethiopia',
                'region_code' => 'ET',
                'latitude' => 8.9806,
                'longitude' => 38.7578,
                'map_zoom' => 5,
                'highlight_radius' => 300000,
            ],
            'dyslexia-organization-kenya' => [
                'membership_level' => 'Contributor',
                'directory_card_title' => 'Dyslexia Organisation Kenya',
                'directory_location' => 'Kenya',
                'directory_address' => 'Kenya',
                'directory_description' => 'A Kenyan nonprofit advancing dyslexia and neurodiversity awareness, early identification, training, and policy reform.',
                'directory_image_path' => '/assets/directory/kenya-logo.png',
                'region_code' => 'KE',
                'latitude' => -1.2921,
                'longitude' => 36.8219,
                'map_zoom' => 5,
                'highlight_radius' => 280000,
            ],
            'turkey-dyslexia-foundation' => [
                'directory_location' => 'Turkey',
                'directory_address' => 'Turkey',
                'directory_description' => 'A Turkish foundation supporting children with specific learning differences while advancing public awareness and educator preparation.',
                'directory_image_path' => '/assets/directory/turkish-dyslexia-foundation-logo.png',
                'region_code' => 'TR',
                'latitude' => 39.9334,
                'longitude' => 32.8597,
                'map_zoom' => 5,
                'highlight_radius' => 300000,
            ],
            'brazilian-dyslexia-association' => [
                'directory_location' => 'Brazil',
                'directory_address' => 'Brazil',
                'directory_description' => 'A Brazilian nonprofit supporting people with dyslexia and other learning disorders through information, assessment, and advocacy.',
                'directory_image_path' => '/assets/directory/brazilian-dyslexia-association-logo.png',
                'region_code' => 'BR',
                'latitude' => -15.7939,
                'longitude' => -47.8828,
                'map_zoom' => 4,
                'highlight_radius' => 420000,
            ],
            'center-for-child-evaluation-and-teaching-kuwait' => [
                'directory_card_title' => 'CCET, Kuwait',
                'directory_location' => 'Kuwait',
                'directory_address' => 'Kuwait',
                'directory_description' => 'CCET provides specialist assessment, educational services, and professional training related to specific learning disabilities.',
                'directory_image_path' => '/assets/directory/kuwait-logo.png',
                'region_code' => 'KW',
                'latitude' => 29.3759,
                'longitude' => 47.9774,
                'map_zoom' => 5,
                'highlight_radius' => 230000,
            ],
            'dr-anjali-morris-education-health-foundation' => [
                'directory_location' => 'Pune, India',
                'directory_address' => 'Pune, India',
                'directory_description' => 'A Pune-based not-for-profit supporting students with specific learning disabilities and ADHD through assessment, intervention, and educator training.',
                'directory_image_path' => '/assets/directory/dr-anjali-morris-foundation-logo.png',
                'region_code' => 'IN',
                'latitude' => 28.6139,
                'longitude' => 77.2090,
                'map_zoom' => 4,
                'highlight_radius' => 360000,
            ],
            'dyslexia-foundation' => [
                'directory_card_title' => 'The Dyslexia Foundation, UK',
                'directory_location' => 'United Kingdom',
                'directory_address' => 'United Kingdom',
                'directory_description' => 'A UK national charity supporting dyslexic adults across education, employment, health, and welfare.',
                'directory_image_path' => '/assets/directory/uk-logo.png',
                'region_code' => 'GB',
                'latitude' => 53.4858,
                'longitude' => -3.0176,
                'map_zoom' => 5,
                'highlight_radius' => 260000,
            ],
            'maharashtra-dyslexia-association' => [
                'directory_card_title' => 'Maharashtra Dyslexia Association',
                'directory_location' => 'Mumbai, India',
                'directory_address' => 'Mumbai, India',
                'directory_description' => 'MDA advances assessment, remediation, training, and advocacy for individuals with specific learning disabilities in India.',
                'directory_image_path' => '/assets/directory/maharashtra-dyslexia-association-logo.svg',
                'region_code' => 'IN',
                'latitude' => 19.0760,
                'longitude' => 72.8777,
                'map_zoom' => 5,
                'highlight_radius' => 260000,
            ],
            'pathways-foundation-ltd' => [
                'directory_card_title' => 'Pathways Foundation, Hong Kong',
                'directory_location' => 'Hong Kong',
                'directory_address' => 'Hong Kong',
                'directory_description' => 'A Hong Kong charity operating learning centres that provide evidence-based intervention, assessment, and therapy for students with dyslexia.',
                'directory_image_path' => '/assets/directory/hong-kong-logo.png',
                'region_code' => 'HK',
                'latitude' => 22.3193,
                'longitude' => 114.1694,
                'map_zoom' => 6,
                'highlight_radius' => 140000,
            ],
            'dyslexia-association-of-singapore' => [
                'directory_location' => 'Singapore',
                'directory_address' => 'Singapore',
                'directory_description' => 'A social enterprise providing assessment, specialised education, and intervention programmes across Singapore.',
                'directory_image_path' => '/assets/directory/singapore-logo.png',
                'region_code' => 'SG',
                'latitude' => 1.3521,
                'longitude' => 103.8198,
                'map_zoom' => 6,
                'highlight_radius' => 160000,
            ],
        ];

        $profiles = [
            [
                'profile_type' => 'member',
                'slug' => 'africa-dyslexia-organization',
                'organization_name' => 'Africa Dyslexia Organization',
                'membership_level' => 'Associate',
                'country' => 'Ghana',
                'region' => 'Africa',
                'flag_emoji' => 'GH',
                'hero_asset_path' => $asset('members/africa-dyslexia-organisation-logo.png'),
                'hero_asset_alt' => 'Africa Dyslexia Organization logo',
                'hero_asset_mode' => 'logo',
                'is_wide_logo' => true,
                'primary_contact_name' => 'Rosalin Abigail Kyere-Nartey',
                'primary_contact_role' => 'Founder and Executive Director',
                'email' => 'info@africadyslexia.org; rosalin@africadyslexia.org',
                'website_url' => 'https://www.africadyslexia.org',
                'record_title' => 'Africa Dyslexia Organization - Associate Member',
                'record_summary' => 'Africa Dyslexia Organization is listed as an <span class="gn-level-inline gn-level-inline--associate">Associate</span> member of the IDA Global Network.',
                'organization_logo_path' => $asset('members/africa-dyslexia-organisation-logo.png'),
                'representative_name' => 'Rosalin Abigail Kyere-Nartey',
                'representative_role' => 'Founder and Executive Director',
                'representative_image_path' => $asset('members/rosalin-abigail-kyere-nartey.jpg'),
                'leader_bio' => 'Rosalin Abigail Kyere-Nartey founded Africa Dyslexia Organization after being diagnosed with dyslexia as an adult. She now leads cross-African advocacy, awareness, and educator support work focused on earlier identification and more equitable learning access.',
                'organization_profile' => 'Founded in 2020, Africa Dyslexia Organization is a pan-African nonprofit advancing early identification, structured literacy, teacher development, public awareness, and inclusive policy engagement.',
                'impact_title' => 'Reach and impact',
                'impact_metrics' => [
                    ['value' => '5,000+', 'label' => 'Educators trained'],
                    ['value' => '330+', 'label' => 'Advocates connected'],
                    ['value' => '38', 'label' => 'Countries represented'],
                    ['value' => '2020', 'label' => 'Year founded'],
                ],
                'profile_links' => [
                    ['label' => 'Website', 'url' => 'https://www.africadyslexia.org'],
                    ['label' => 'LinkedIn', 'url' => 'https://www.linkedin.com/company/africadyslexiaorg/'],
                    ['label' => 'YouTube', 'url' => 'https://www.youtube.com/@africadyslexiaorg'],
                ],
                'summary' => 'Associate member organization supporting dyslexia awareness, advocacy, and member services in Ghana.',
                'status' => 'active',
                'display_order' => 10,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'australian-dyslexia-association',
                'organization_name' => 'Australian Dyslexia Association',
                'membership_level' => 'Associate',
                'country' => 'Australia',
                'region' => 'Oceania',
                'flag_emoji' => 'AU',
                'primary_contact_name' => 'Jodi Clements',
                'email' => 'jodi.clements@gmail.com',
                'summary' => 'Associate member organization representing dyslexia support and advocacy activity in Australia.',
                'status' => 'active',
                'display_order' => 20,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'bellavista-school',
                'organization_name' => 'Bellavista School',
                'membership_level' => 'Associate',
                'country' => 'South Africa',
                'region' => 'Africa',
                'flag_emoji' => 'ZA',
                'hero_asset_path' => $asset('members/bellavista-share-logo.png'),
                'hero_asset_alt' => 'Bellavista S.H.A.R.E. logo',
                'hero_asset_mode' => 'logo',
                'is_wide_logo' => true,
                'primary_contact_name' => 'Annelize Clark Hendry',
                'primary_contact_role' => 'Director of Programmes',
                'email' => 'annelize.clark@bellavista.org.za',
                'record_title' => 'Bellavista School - Associate Member',
                'record_summary' => 'Bellavista School is listed as an <span class="gn-level-inline gn-level-inline--associate">Associate</span> member of the IDA Global Network.',
                'representative_name' => 'Annelize Clark Hendry',
                'representative_role' => 'Director of Programmes',
                'representative_image_path' => $asset('members/annelize-clark-hendry.png'),
                'organization_profile' => 'Bellavista S.H.A.R.E. extends the school\'s specialist remedial, assessment, and learning-support expertise through evidence-based training and professional development.',
                'impact_title' => 'Specialist education profile',
                'impact_metrics' => [
                    ['value' => 'Johannesburg', 'label' => 'Specialist remedial school base'],
                    ['value' => '2 years', 'label' => 'Flagship remedial education award'],
                    ['value' => 'CPD', 'label' => 'Accredited professional learning'],
                ],
                'profile_links' => [
                    ['label' => 'Member Profile (Word)', 'url' => $asset('members/bellavista-south-africa-profile.docx')],
                ],
                'summary' => 'Associate member organization contributing school-based dyslexia programming and regional collaboration.',
                'status' => 'active',
                'display_order' => 30,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'dyslexia-and-social-support-services-botswana',
                'organization_name' => 'Dyslexia and Social Support Services Botswana',
                'membership_level' => 'Associate',
                'country' => 'Botswana',
                'region' => 'Africa',
                'flag_emoji' => 'BW',
                'hero_asset_path' => $asset('members/botswana-dyslexia-logo.jpg'),
                'hero_asset_alt' => 'Botswana dyslexia logo',
                'hero_asset_mode' => 'logo',
                'primary_contact_name' => 'Letang Giro',
                'primary_contact_role' => 'Member representative',
                'summary' => 'Associate member organization serving learners and families through dyslexia support services in Botswana.',
                'status' => 'active',
                'display_order' => 40,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'dyslexia-ireland',
                'organization_name' => 'Dyslexia Ireland',
                'membership_level' => 'Associate',
                'country' => 'Ireland',
                'region' => 'Europe',
                'flag_emoji' => 'IE',
                'hero_asset_path' => $asset('members/dyslexia-ireland-logo.png'),
                'hero_asset_alt' => 'Dyslexia Ireland logo',
                'hero_asset_mode' => 'logo',
                'is_wide_logo' => true,
                'primary_contact_name' => 'Rosie Bissett',
                'primary_contact_role' => 'CEO',
                'email' => 'rosiebissett@dyslexia.ie',
                'website_url' => 'https://dyslexia.ie/',
                'record_title' => 'Dyslexia Ireland - Associate Member',
                'record_summary' => 'Dyslexia Ireland is listed as an <span class="gn-level-inline gn-level-inline--associate">Associate</span> member of the IDA Global Network.',
                'representative_name' => 'Rosie Bissett',
                'representative_role' => 'CEO, Dyslexia Ireland',
                'representative_image_path' => $asset('members/rosie-bissett.jpg'),
                'leader_bio' => 'Rosie Bissett has served as CEO of Dyslexia Ireland since 2008 and leads the organization\'s nationwide information, assessment, training, awareness, and advocacy services.',
                'organization_profile' => 'Founded in 1972, Dyslexia Ireland is Ireland\'s national representative body for dyslexia and dyscalculia, providing information, assessment, tuition, training, and advocacy.',
                'impact_title' => 'National services and advocacy',
                'impact_metrics' => [
                    ['value' => '1972', 'label' => 'Year founded'],
                    ['value' => 'National', 'label' => 'Representative body'],
                    ['value' => 'Assessment + Tuition', 'label' => 'Specialist support'],
                ],
                'profile_links' => [
                    ['label' => 'Website', 'url' => 'https://dyslexia.ie/'],
                    ['label' => 'Dyslexia Hub', 'url' => 'https://dyslexiahub.ie/'],
                ],
                'summary' => 'Associate member organization with national dyslexia services, professional support, and community outreach.',
                'status' => 'active',
                'display_order' => 50,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'dyslexia-association-of-indonesia',
                'organization_name' => 'Dyslexia Association of Indonesia',
                'membership_level' => 'Associate',
                'country' => 'Indonesia',
                'region' => 'Asia',
                'flag_emoji' => 'ID',
                'hero_asset_path' => $asset('members/dyslexia-association-of-indonesia-logo.jpeg'),
                'hero_asset_alt' => 'Dyslexia Association of Indonesia logo',
                'hero_asset_mode' => 'logo',
                'is_wide_logo' => true,
                'primary_contact_name' => 'Kristiantini Dewi',
                'primary_contact_role' => 'Chairperson',
                'representative_name' => 'Dr. Kristiantini Dewi',
                'representative_role' => 'Chairperson',
                'representative_image_path' => $asset('members/dr-kristiantini-dewi.jpeg'),
                'record_title' => 'Dyslexia Association of Indonesia - Associate Member',
                'record_summary' => 'The Dyslexia Association of Indonesia is listed as an <span class="gn-level-inline gn-level-inline--associate">Associate</span> member of the IDA Global Network.',
                'organization_profile' => 'Founded in December 2009, the Dyslexia Association of Indonesia brings together parents, teachers, educators, physicians, and psychologists to improve awareness, identification, education, and support.',
                'impact_title' => 'Assessment and capacity building',
                'impact_metrics' => [
                    ['value' => '2009', 'label' => 'Year founded'],
                    ['value' => '16 modules', 'label' => 'Teacher programme'],
                    ['value' => 'National', 'label' => 'Training and advocacy reach'],
                ],
                'summary' => 'Associate member organization advancing dyslexia awareness, family support, and educational capacity in Indonesia.',
                'status' => 'active',
                'display_order' => 60,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'dyslexia-science',
                'organization_name' => 'Dyslexia Science',
                'membership_level' => 'Associate',
                'country' => 'Scotland',
                'region' => 'Europe',
                'flag_emoji' => 'GB',
                'primary_contact_name' => 'Gillian Evans',
                'email' => 'evansge@outlook.com',
                'summary' => 'Associate member organization contributing research-informed practice and public engagement from Scotland.',
                'status' => 'active',
                'display_order' => 70,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'fana-ethiopia',
                'organization_name' => 'FANA-Ethiopia',
                'membership_level' => 'Associate',
                'country' => 'Ethiopia',
                'region' => 'Africa',
                'flag_emoji' => 'ET',
                'hero_asset_path' => $asset('members/fana-ethiopia-logo.jpg'),
                'hero_asset_alt' => 'FANA-Ethiopia logo',
                'hero_asset_mode' => 'logo',
                'primary_contact_name' => 'Abebayehu Messele Mekonnen',
                'primary_contact_role' => 'Founder and CEO',
                'representative_name' => 'Dr. Abebayehu Messele Mekonnen',
                'representative_role' => 'Founder and CEO',
                'representative_image_path' => $asset('members/dr-abebayehu-mekonnen.jpg'),
                'summary' => 'Associate member organization focused on inclusive support, awareness, and dyslexia learning access in Ethiopia.',
                'status' => 'active',
                'display_order' => 80,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'dyslexia-organization-kenya',
                'organization_name' => 'Kenya Dyslexia Association',
                'membership_level' => 'Associate',
                'country' => 'Kenya',
                'region' => 'Africa',
                'flag_emoji' => 'KE',
                'hero_asset_path' => $asset('members/kenya-dyslexia-organization-logo.jpg'),
                'hero_asset_alt' => 'Kenya Dyslexia Association logo',
                'hero_asset_mode' => 'logo',
                'is_wide_logo' => true,
                'primary_contact_name' => 'Phyllis Munyi',
                'primary_contact_role' => 'CEO',
                'email' => 'phyllis.munyi8@gmail.com',
                'summary' => 'Associate member organization leading dyslexia advocacy, screening, and training initiatives in Kenya.',
                'status' => 'active',
                'display_order' => 90,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'turkey-dyslexia-foundation',
                'organization_name' => 'Turkey Dyslexia Foundation',
                'membership_level' => 'Associate',
                'country' => 'Turkey',
                'region' => 'Europe',
                'flag_emoji' => 'TR',
                'primary_contact_name' => 'Tuncer Yavuz',
                'email' => 'info@tudiv.org.tr',
                'summary' => 'Associate member organization supporting awareness and national coordination for dyslexia in Turkey.',
                'status' => 'active',
                'display_order' => 100,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'brazilian-dyslexia-association',
                'organization_name' => 'Brazilian Dyslexia Association',
                'membership_level' => 'Contributor',
                'country' => 'Brazil',
                'region' => 'South America',
                'flag_emoji' => 'BR',
                'primary_contact_name' => 'Angela Nico',
                'email' => 'contato@dislexia.org.br',
                'summary' => 'Contributor-level member organization expanding dyslexia support and professional development in Brazil.',
                'status' => 'active',
                'display_order' => 110,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'center-for-child-evaluation-and-teaching-kuwait',
                'organization_name' => 'Centre for Child Evaluation & Teaching (CCET)',
                'membership_level' => 'Contributor',
                'country' => 'Kuwait',
                'region' => 'Middle East',
                'flag_emoji' => 'KW',
                'hero_asset_path' => $asset('members/ccet-logo.png'),
                'hero_asset_alt' => 'CCET logo',
                'hero_asset_mode' => 'logo',
                'primary_contact_name' => 'Abir Al-Sharhan',
                'primary_contact_role' => 'Assistant Director for Technical Affairs',
                'email' => 'a.sharhan@ccetkuwait.org',
                'record_title' => 'Centre for Child Evaluation & Teaching (CCET) - Contributor Member',
                'record_summary' => 'CCET is listed as a <span class="gn-level-inline gn-level-inline--contributor">Contributor</span> member of the IDA Global Network.',
                'organization_logo_path' => $asset('members/ccet-logo.png'),
                'representative_name' => 'Dr. Abir Al-Sharhan',
                'representative_role' => 'Assistant Director for Technical Affairs',
                'representative_image_path' => $asset('members/dr-abir-al-sharhan.jpg'),
                'organization_profile' => 'CCET is a nonprofit organization specializing in specific learning disabilities since 1984, providing assessment, educational services, specialist training, and community awareness.',
                'impact_title' => 'Specialist service profile',
                'impact_metrics' => [
                    ['value' => '1984', 'label' => 'Established'],
                    ['value' => 'Assessment + Education', 'label' => 'Core services'],
                    ['value' => 'Regional', 'label' => 'Knowledge exchange reach'],
                ],
                'summary' => 'Contributor-level member organization with technical expertise in child evaluation, teaching, and dyslexia support.',
                'status' => 'active',
                'display_order' => 120,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'dr-anjali-morris-education-health-foundation',
                'organization_name' => 'Dr. Anjali Morris Education & Health Foundation',
                'membership_level' => 'Contributor',
                'country' => 'India',
                'region' => 'Asia',
                'flag_emoji' => 'IN',
                'primary_contact_name' => 'Tanima Sarkar',
                'email' => 'tanima@morrisfoundation.in',
                'summary' => 'Contributor-level member organization serving educational and health inclusion goals for dyslexic learners in India.',
                'status' => 'active',
                'display_order' => 130,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'dyslexia-foundation',
                'organization_name' => 'Dyslexia Foundation',
                'membership_level' => 'Contributor',
                'country' => 'England',
                'region' => 'Europe',
                'flag_emoji' => 'GB',
                'hero_asset_path' => $asset('members/dyslexia-foundation-uk-logo.jpg'),
                'hero_asset_alt' => 'Dyslexia Foundation UK logo',
                'hero_asset_mode' => 'logo',
                'primary_contact_name' => 'Steve O\'Brien',
                'primary_contact_role' => 'CEO',
                'email' => 'steve@dyslexiafoundation.co.uk',
                'summary' => 'Contributor-level member organization and a key leadership voice in the Global Network community.',
                'status' => 'active',
                'display_order' => 140,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'maharashtra-dyslexia-association',
                'organization_name' => 'Maharashtra Dyslexia Association',
                'membership_level' => 'Contributor',
                'country' => 'India',
                'region' => 'Asia',
                'flag_emoji' => 'IN',
                'hero_asset_path' => $asset('members/maharashtra-dyslexia-association-logo.jpg'),
                'hero_asset_alt' => 'Maharashtra Dyslexia Association logo',
                'hero_asset_mode' => 'logo',
                'is_wide_logo' => true,
                'primary_contact_name' => 'Kate Currawalla',
                'primary_contact_role' => 'Founder President and CEO',
                'email' => 'kcurrawalla@gmail.com',
                'representative_name' => 'Kate Currawalla',
                'representative_role' => 'Founder President and CEO',
                'representative_image_path' => $asset('members/kate-currawalla.jpg'),
                'leader_bio' => 'Kate Currawalla founded Maharashtra Dyslexia Association and has led sustained advocacy, training partnerships, and stronger service access for children with specific learning disabilities.',
                'summary' => 'Contributor-level member organization supporting dyslexia leadership, advocacy, and practitioner development in India.',
                'status' => 'active',
                'display_order' => 150,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'pathways-foundation-ltd',
                'organization_name' => 'Pathways Foundation Ltd.',
                'membership_level' => 'Contributor',
                'country' => 'Hong Kong',
                'region' => 'Asia',
                'flag_emoji' => 'HK',
                'hero_asset_path' => $asset('members/pathways-foundation-logo.png'),
                'hero_asset_alt' => 'Pathways Foundation logo',
                'hero_asset_mode' => 'logo',
                'is_wide_logo' => true,
                'primary_contact_name' => 'Lucille Wong',
                'primary_contact_role' => 'CEO',
                'email' => 'lucille.wong@pathways.org.hk',
                'representative_name' => 'Lucille Wong',
                'representative_role' => 'CEO, Pathways Foundation',
                'representative_image_path' => $asset('members/lucille-wong.jpg'),
                'summary' => 'Contributor-level member organization supporting dyslexia access, community learning, and leadership in Hong Kong.',
                'status' => 'active',
                'display_order' => 160,
            ],
            [
                'profile_type' => 'member',
                'slug' => 'dyslexia-association-of-singapore',
                'organization_name' => 'Dyslexia Association of Singapore',
                'membership_level' => 'Partner',
                'country' => 'Singapore',
                'region' => 'Asia',
                'flag_emoji' => 'SG',
                'primary_contact_name' => 'Lee Siang',
                'primary_contact_role' => 'CEO',
                'record_title' => 'Dyslexia Association of Singapore - Partner Member',
                'record_summary' => 'The Dyslexia Association of Singapore is listed as a <span class="gn-level-inline gn-level-inline--partner">Partner</span> member of the IDA Global Network.',
                'representative_name' => 'Lee Siang',
                'representative_role' => 'Chief Executive Officer',
                'representative_image_path' => $asset('members/lee-siang.jpg'),
                'summary' => 'Partner-level Global Network member organization with leadership roles across governance and programme collaboration.',
                'status' => 'active',
                'display_order' => 170,
            ],
            [
                'profile_type' => 'friend',
                'slug' => 'unlock-learning-south-africa',
                'organization_name' => 'Unlock Learning South Africa',
                'membership_level' => 'Friend',
                'level_label' => 'At-Large Friend',
                'country' => 'South Africa',
                'region' => 'Africa',
                'flag_emoji' => 'ZA',
                'hero_asset_path' => $asset('members/merlaine-yeo.jpg'),
                'hero_asset_alt' => 'Portrait of Merlaine Yeo',
                'hero_asset_mode' => 'portrait',
                'primary_contact_name' => 'Merlaine Yeo',
                'primary_contact_role' => 'Director',
                'email' => 'merlaineyeo@gmail.com',
                'profile_heading' => 'Global Network Friend Profile',
                'profile_subheading' => 'At-Large Friend record and organizational background.',
                'record_title' => 'Unlock Learning South Africa - At-Large Friend',
                'record_summary' => 'Merlaine Yeo, Director of Unlock Learning South Africa, is listed as an <span class="gn-level-inline gn-level-inline--friend">At-Large Friend</span> of the IDA Global Network.',
                'organization_logo_path' => $asset('members/unlock-learning-south-africa-logo.jpg'),
                'representative_name' => 'Merlaine Yeo',
                'representative_role' => 'Director, Unlock Learning South Africa',
                'representative_image_path' => $asset('members/merlaine-yeo.jpg'),
                'leader_bio' => 'Merlaine Yeo is a South African educational leader with more than 25 years of experience spanning teaching, curriculum development, inclusive education, learner support, and school management.',
                'organization_profile' => 'Unlock Learning South Africa is a registered nonprofit working to improve access to support for learners with dyslexia and related barriers to learning, particularly in under-resourced schools.',
                'impact_title' => 'Focus and organizational profile',
                'impact_metrics' => [
                    ['value' => '25+ years', 'label' => 'Educational experience'],
                    ['value' => '2025', 'label' => 'Year established'],
                    ['value' => 'SIAS', 'label' => 'Policy and support alignment'],
                ],
                'profile_links' => [
                    ['label' => 'Merlaine Yeo on LinkedIn', 'url' => 'https://www.linkedin.com/in/merlaine-yeo-0601b4173'],
                ],
                'summary' => 'Friend of the Global Network with an active role in inclusive education and learning support.',
                'status' => 'active',
                'display_order' => 300,
            ],
            [
                'profile_type' => 'friend',
                'slug' => 'ahmed-al-shiha',
                'organization_name' => 'Kuwait Dyslexia Association',
                'membership_level' => 'Friend',
                'level_label' => 'At-Large Friend',
                'country' => 'Kuwait',
                'region' => 'Middle East',
                'flag_emoji' => 'KW',
                'hero_asset_path' => $asset('members/dr-ahmed-al-shiha.jpeg'),
                'hero_asset_alt' => 'Portrait of Ahmed Al Shiha',
                'hero_asset_mode' => 'portrait',
                'primary_contact_name' => 'Dr. Ahmed Al Shiha',
                'primary_contact_role' => 'Chairman of the Board',
                'profile_heading' => 'Global Network Friend Profile',
                'profile_subheading' => 'At-Large Friend record and organizational background.',
                'record_title' => 'Dr. Ahmed Al Shiha - At-Large Friend',
                'record_summary' => 'Dr. Ahmed Al Shiha is listed as an <span class="gn-level-inline gn-level-inline--friend">At-Large Friend</span> of the IDA Global Network.',
                'summary' => 'At-Large Friend profile linked to Kuwait Dyslexia Association leadership.',
                'status' => 'active',
                'display_order' => 310,
            ],
            [
                'profile_type' => 'friend',
                'slug' => 'marlon-ralph-nyakabau',
                'organization_name' => 'Dyslexia in Africa Trust',
                'membership_level' => 'Friend',
                'level_label' => 'At-Large Friend',
                'country' => 'Zimbabwe',
                'region' => 'Africa',
                'flag_emoji' => 'ZW',
                'hero_asset_path' => $asset('members/dr-marlon-ralph-nyakabau.jpeg'),
                'hero_asset_alt' => 'Portrait of Marlon-Ralph Nyakabau',
                'hero_asset_mode' => 'portrait',
                'primary_contact_name' => 'Dr. Marlon-Ralph Nyakabau',
                'primary_contact_role' => 'Founder and Director',
                'profile_heading' => 'Global Network Friend Profile',
                'profile_subheading' => 'At-Large Friend record and organizational background.',
                'record_title' => 'Dr. Marlon-Ralph Nyakabau - At-Large Friend',
                'record_summary' => 'Dr. Marlon-Ralph Nyakabau is listed as an <span class="gn-level-inline gn-level-inline--friend">At-Large Friend</span> of the IDA Global Network.',
                'organization_logo_path' => $asset('members/dyslexia-in-africa-trust-logo.jpeg'),
                'representative_name' => 'Dr. Marlon-Ralph Nyakabau',
                'representative_role' => 'Founder and Director, Dyslexia in Africa Trust',
                'representative_image_path' => $asset('members/dr-marlon-ralph-nyakabau.jpeg'),
                'leader_bio' => 'Dr. Marlon-Ralph Nyakabau is a medical doctor and digital-health consultant with more than a decade of experience applying technology, including artificial intelligence, to health.',
                'organization_profile' => 'Dyslexia in Africa Trust is a Zimbabwean nonprofit formed by teachers, parents, therapists, and researchers committed to raising dyslexia awareness and improving access to diagnostic and remedial services.',
                'impact_title' => 'Experience and organizational activity',
                'impact_metrics' => [
                    ['value' => '10+ years', 'label' => 'Health technology experience'],
                    ['value' => '2', 'label' => 'Conferences convened'],
                    ['value' => 'Annual', 'label' => 'Sporting tournaments organized'],
                ],
                'profile_links' => [
                    ['label' => 'Dr. Marlon profile (Word)', 'url' => $asset('members/dr-marlon-profile.docx')],
                    ['label' => 'Trust profile (Word)', 'url' => $asset('members/dyslexia-in-africa-trust-profile.docx')],
                ],
                'summary' => 'At-Large Friend profile linked to Dyslexia in Africa Trust.',
                'status' => 'active',
                'display_order' => 320,
            ],
            [
                'profile_type' => 'friend',
                'slug' => 'blessing-ingyape',
                'organization_name' => 'Dyslexia Project Africa',
                'membership_level' => 'Friend',
                'level_label' => 'At-Large Friend',
                'country' => 'Nigeria',
                'region' => 'Africa',
                'flag_emoji' => 'NG',
                'hero_asset_path' => $asset('members/blessing-ingyape.jpeg'),
                'hero_asset_alt' => 'Portrait of Blessing Ingyape',
                'hero_asset_mode' => 'portrait',
                'primary_contact_name' => 'Blessing Ingyape',
                'primary_contact_role' => 'Co-Founder',
                'profile_heading' => 'Global Network Friend Profile',
                'profile_subheading' => 'At-Large Friend record and organizational background.',
                'record_title' => 'Blessing Ingyape - At-Large Friend',
                'record_summary' => 'Blessing Ingyape is listed as an <span class="gn-level-inline gn-level-inline--friend">At-Large Friend</span> of the IDA Global Network.',
                'summary' => 'At-Large Friend profile linked to Dyslexia Project Africa.',
                'status' => 'active',
                'display_order' => 330,
            ],
        ];

        foreach ($profiles as $profile) {
            $profile = array_merge(
                $profile,
                $directoryOverrides[$profile['slug']] ?? [],
            );

            DashboardMemberProfile::query()->updateOrCreate(
                ['slug' => $profile['slug']],
                $profile
            );
        }
    }
}
