<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Accreditation Process Workspace | IDA GN Central</title>
  <style>
    :root{color-scheme:light;--navy:#16345b;--deep:#102846;--blue:#2367a6;--teal:#1f9a9c;--gold:#d7a642;--ink:#182231;--muted:#647286;--line:#d8e0ea;--soft:#f3f7fa;--white:#fff;--success:#287a55;--danger:#b54343;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    *{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--soft)}button,input,select,textarea{font:inherit}.shell{min-height:100vh;display:grid;grid-template-columns:260px minmax(0,1fr)}
    .sidebar{position:sticky;top:0;height:100vh;overflow:auto;display:flex;flex-direction:column;gap:24px;padding:22px 18px;color:#fff;background:linear-gradient(180deg,var(--navy),var(--deep))}.brand{display:flex;align-items:center;gap:12px}.brand img{width:46px;height:46px;object-fit:contain;padding:4px;border-radius:8px;background:#fff}.brand strong{display:block;font-size:15px}.brand span{display:block;margin-top:3px;color:#bfd0e2;font-size:12px}.nav{display:grid;gap:6px}.nav>a,.nav summary{display:flex;align-items:center;padding:10px 11px;border-radius:6px;color:#d9e5f1;font-size:14px;text-decoration:none}.nav>a:hover{color:#fff;background:rgba(255,255,255,.14);box-shadow:inset 3px 0 0 var(--gold)}summary{list-style:none;cursor:pointer}summary::-webkit-details-marker{display:none}.nav summary::after{content:"›";margin-left:auto;transition:transform 160ms ease}.nav details[open]>summary::after{transform:rotate(90deg);color:#64ddd4}.nav details>summary{border:1px solid rgba(31,154,156,.30);background:linear-gradient(135deg,rgba(31,154,156,.28),rgba(35,103,166,.13));backdrop-filter:blur(12px);box-shadow:0 7px 17px rgba(3,15,30,.16),inset 0 1px 0 rgba(255,255,255,.08);transition:transform 140ms ease,background 180ms ease,box-shadow 180ms ease}.nav details[open]>summary{color:#fff;background:linear-gradient(135deg,rgba(31,154,156,.52),rgba(35,103,166,.26));box-shadow:inset 3px 0 0 #58d1c9,0 9px 21px rgba(3,15,30,.22)}.nav details>summary:active{transform:translateY(2px) scale(.985);box-shadow:inset 0 3px 8px rgba(0,0,0,.24)}.nav-sub{display:grid;gap:7px;margin:5px 0 8px 27px}.nav-sub a{padding:7px 9px;border-radius:6px;color:#c7d7e8;background:rgba(255,255,255,.06);text-decoration:none;font-size:12px}.nav-sub a:hover,.nav-sub a.active{color:#fff;background:linear-gradient(135deg,rgba(31,154,156,.24),rgba(255,255,255,.09));box-shadow:inset 2px 0 0 #58d1c9}.sidebar-note{margin-top:auto;padding:14px;border:1px solid rgba(255,255,255,.18);border-radius:8px;color:#d7e2ee;background:rgba(255,255,255,.09);font-size:12px;line-height:1.5}
    .main{min-width:0}.topbar{min-height:72px;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:13px 28px;border-bottom:1px solid var(--line);background:#fff}.topbar h1{margin:0;font-size:21px}.topbar p{margin:3px 0 0;color:var(--muted);font-size:12px}.role-switch{display:flex;padding:3px;border-radius:8px;background:#e9eff4}.role-switch button{padding:7px 11px;border:0;border-radius:6px;color:var(--muted);background:transparent;font-size:11px;font-weight:800;cursor:pointer}.role-switch button.active{color:#fff;background:var(--navy)}
    .content{max-width:1380px;margin:0 auto;padding:27px}.notice{display:flex;align-items:center;gap:11px;margin-bottom:17px;padding:13px 16px;border:1px solid #e6d19a;border-radius:10px;color:#66562d;background:#fff8e7;font-size:12px}.notice strong{color:#4c401f}.case-head{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:22px;align-items:center;padding:25px;border-radius:16px;color:#fff;background:linear-gradient(115deg,var(--navy),#235f8d);box-shadow:0 12px 34px rgba(22,52,91,.16)}.case-head .eyebrow{margin:0 0 7px;color:#f3d486;font-size:10px;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.case-head h2{margin:0;font-size:27px}.case-head p{margin:7px 0 0;color:#dbe8f3;font-size:13px}.case-stats{display:grid;grid-template-columns:repeat(3,95px);gap:8px}.case-stat{padding:12px;border:1px solid rgba(255,255,255,.18);border-radius:9px;text-align:center;background:rgba(255,255,255,.09)}.case-stat strong{display:block;font-size:20px}.case-stat span{display:block;margin-top:3px;color:#c9d8e6;font-size:9px;text-transform:uppercase}
    .section-head{display:flex;align-items:end;justify-content:space-between;gap:18px;margin:32px 0 14px}.section-head h2{margin:0;color:var(--navy);font-size:22px}.section-head p{margin:5px 0 0;color:var(--muted);font-size:12px}.section-head a{color:var(--blue);font-size:11px;font-weight:800;text-decoration:none}
    .journey{display:grid;grid-template-columns:repeat(7,minmax(115px,1fr));overflow:auto;padding:5px 2px 13px}.phase{position:relative;min-width:115px;padding:0 8px 0 0}.phase:not(:last-child)::after{content:"";position:absolute;left:34px;right:0;top:15px;height:2px;background:#cbd6df}.phase.complete:not(:last-child)::after{background:var(--teal)}.phase-dot{position:relative;z-index:1;width:31px;height:31px;display:grid;place-items:center;border:3px solid var(--soft);border-radius:50%;color:#7f8b99;background:#d7e0e8;font-size:10px;font-weight:900}.phase.complete .phase-dot{color:#fff;background:var(--teal)}.phase.current .phase-dot{color:#18324f;background:var(--gold);box-shadow:0 0 0 4px #fff1c9}.phase strong{display:block;margin-top:9px;color:var(--navy);font-size:11px}.phase span{display:block;margin-top:3px;color:var(--muted);font-size:9px;line-height:1.35}
    .workspace{display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:18px;align-items:start}.panel{overflow:hidden;border:1px solid var(--line);border-radius:14px;background:#fff;box-shadow:0 7px 24px rgba(22,52,91,.05)}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:16px 18px;border-bottom:1px solid var(--line);background:#eef4f8}.panel-head h3{margin:0;color:var(--navy);font-size:15px}.panel-head span{color:var(--muted);font-size:10px}.standards{display:grid}.standard{border-bottom:1px solid var(--line)}.standard:last-child{border-bottom:0}.standard summary{display:grid;grid-template-columns:36px minmax(0,1fr) auto auto;gap:12px;align-items:center;padding:14px 17px}.standard summary:hover{background:#fafcfd}.standard-number{width:32px;height:32px;display:grid;place-items:center;border-radius:9px;color:var(--blue);background:#eaf2fb;font-size:10px;font-weight:900}.standard-title strong{display:block;color:var(--navy);font-size:12px}.standard-title span{display:block;margin-top:3px;color:var(--muted);font-size:10px}.meter{width:90px;height:7px;overflow:hidden;border-radius:99px;background:#e2e9ef}.meter i{display:block;height:100%;background:var(--teal)}.standard-score{min-width:42px;color:var(--navy);font-size:11px;font-weight:850;text-align:right}.criteria{padding:0 17px 16px 65px}.criterion{display:grid;grid-template-columns:minmax(0,1fr) 110px;gap:14px;align-items:center;padding:11px 0;border-top:1px dashed #dce3ea}.criterion p{margin:0;color:#3b4d62;font-size:11px;line-height:1.45}.criterion small{display:block;margin-top:3px;color:var(--muted);font-size:9px}.criterion select{width:100%;min-height:34px;padding:6px 8px;border:1px solid #cbd6e1;border-radius:7px;color:var(--navy);background:#fff;font-size:10px;font-weight:750}.criterion select:disabled{opacity:.75;background:#f2f5f7}
    .side-stack{display:grid;gap:16px}.score-card{padding:20px;border-radius:14px;color:#fff;background:linear-gradient(145deg,var(--navy),#245f8b)}.score-card .label{color:#c9d8e6;font-size:10px;text-transform:uppercase;letter-spacing:.08em}.score-main{display:flex;align-items:end;justify-content:space-between;margin:9px 0 13px}.score-main strong{font-size:34px}.score-main span{color:#d7e4ef;font-size:11px}.score-track{height:8px;overflow:hidden;border-radius:99px;background:rgba(255,255,255,.18)}.score-track i{display:block;width:0;height:100%;background:var(--gold);transition:width 180ms ease}.legend{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin-top:15px}.legend div{padding:7px;border-radius:6px;text-align:center;background:rgba(255,255,255,.08)}.legend strong{display:block;font-size:12px}.legend span{display:block;color:#cbdbe8;font-size:8px}.score-card p{margin:14px 0 0;color:#dbe8f3;font-size:10px;line-height:1.5}
    .activity{padding:17px}.activity-list{display:grid;gap:13px}.activity-item{display:grid;grid-template-columns:9px 1fr;gap:10px}.activity-dot{width:8px;height:8px;margin-top:4px;border-radius:50%;background:var(--teal)}.activity-item strong{display:block;color:var(--navy);font-size:11px}.activity-item p{margin:3px 0 0;color:var(--muted);font-size:9px;line-height:1.45}.action-box{padding:17px}.action-box label{display:block;margin-bottom:6px;color:var(--navy);font-size:10px;font-weight:800}.action-box textarea{width:100%;min-height:92px;padding:10px;border:1px solid #cbd6e1;border-radius:8px;resize:vertical;font-size:11px}.action-box button{width:100%;min-height:38px;margin-top:9px;border:0;border-radius:7px;color:#fff;background:var(--navy);font-size:10px;font-weight:800;cursor:pointer}.source-note{margin-top:18px;padding:14px 16px;border-radius:9px;color:var(--muted);background:#e9eff4;font-size:10px;line-height:1.5}.source-note a{color:var(--blue);font-weight:800}
    .nav details[open]>summary{box-shadow:inset 3px 0 0 var(--gold),0 9px 21px rgba(3,15,30,.22)}.nav-sub a:hover,.nav-sub a.active{box-shadow:inset 2px 0 0 var(--gold)}
    @@media(max-width:1050px){.workspace{grid-template-columns:1fr}.side-stack{grid-template-columns:1fr 1fr}.case-head{grid-template-columns:1fr}.case-stats{grid-template-columns:repeat(3,1fr)}}@@media(max-width:820px){.shell{grid-template-columns:1fr}.sidebar{position:static;height:auto}.nav{grid-template-columns:repeat(3,1fr)}.nav-sub,.sidebar-note{display:none}}@@media(max-width:650px){.topbar{padding:14px 18px;align-items:flex-start;flex-direction:column}.content{padding:18px}.case-stats,.side-stack{grid-template-columns:1fr}.standard summary{grid-template-columns:36px 1fr auto}.meter{display:none}.criteria{padding-left:17px}.criterion{grid-template-columns:1fr}.case-head{padding:20px}}
  </style>
  <link rel="stylesheet" href="{{ asset('assets/dashboard/gn-central/preview-assets') }}/gn-central-navigation.css">
</head>
<body>
  <div class="shell">
    <aside class="sidebar"><div class="brand"><img src="{{ asset('assets/dashboard/gn-central/preview-assets') }}/ida-global-network-logo.png" alt="IDA Global Network logo"><div><strong>Global Network Central</strong><span>Accreditation Case</span></div></div>
      <nav class="nav"><a data-icon="⌂" href="{{ route('dashboard.index') }}">Home</a><a data-icon="▤" href="{{ route('dashboard.membership-applications.index') }}">Applications</a><a data-icon="♛" data-section="leadership" href="{{ route('dashboard.member-leadership.index') }}">Member Leadership</a>
        <a data-icon="◫" href="{{ route('dashboard.member-operations.index') }}">Member Operations</a><a data-icon="▥" data-section="resources" href="{{ route('dashboard.membership-options.index') }}">Resources</a><details class="current-section" data-section="accreditation" open><summary data-icon="✪">Institutional Accreditation</summary><div class="nav-sub"><a href="{{ route('dashboard.accreditation.index') }}">Overview</a><a href="{{ route('dashboard.accreditation-application.index') }}">Apply online</a><a class="active" href="#">Process workspace</a><a href="{{ route('dashboard.accreditation-reviewer-training.index') }}">Reviewer training</a></div></details><a data-icon="▦" href="#">Reports</a><a data-icon="⚙" href="{{ route('dashboard.authority-levels.index') }}">Authority &amp; Profiles</a></nav>
      <div class="sidebar-note">Applicants and assigned reviewers share one view of milestones, evidence readiness, standards, findings, and next actions.</div>
    </aside>
    <main class="main">
      <header class="topbar"><div><h1>Accreditation Process Workspace</h1><p>Follow one application from acceptance through committee decision.</p></div><div class="role-switch" aria-label="Workspace view"><button class="active" data-role="applicant" type="button">Applicant view</button><button data-role="reviewer" type="button">Reviewer view</button></div></header>
      <div class="content">
        <div class="notice"><strong>Illustrative workspace:</strong> this demonstrates the live process using browser-saved progress. Production records require the GN Central submission backend.</div>
        <section class="case-head"><div><p class="eyebrow">Active accreditation case · IA-2026-001</p><h2>Global Network Member Institution</h2><p>Primary contact · Assigned mentor · Reviewer pending</p></div><div class="case-stats"><div class="case-stat"><strong>3/7</strong><span>Current stage</span></div><div class="case-stat"><strong id="evidenceCount">0/37</strong><span>Criteria rated</span></div><div class="case-stat"><strong id="overallPercent">0%</strong><span>Score recorded</span></div></div></section>

        <div class="section-head"><div><h2>Accreditation journey</h2><p>Everyone sees the same milestone and understands what happens next.</p></div><a href="{{ asset('assets/dashboard/gn-central/GN Central') }}/Institutional Accreditation/Current Packet/Application Packet/IDA_InstitutionalAccreditationPlan_Version 2.0_2024.pdf">Open process plan</a></div>
        <section class="journey" aria-label="Accreditation process stages">
          <div class="phase complete"><div class="phase-dot">✓</div><strong>Application</strong><span>Initial application accepted</span></div>
          <div class="phase complete"><div class="phase-dot">✓</div><strong>Mentor assigned</strong><span>Support and criteria guidance</span></div>
          <div class="phase current"><div class="phase-dot">3</div><strong>Self-study</strong><span>Evidence inventory in progress</span></div>
          <div class="phase"><div class="phase-dot">4</div><strong>Evidence review</strong><span>Mentor readiness confirmation</span></div>
          <div class="phase"><div class="phase-dot">5</div><strong>Site visit</strong><span>Interviews and verification</span></div>
          <div class="phase"><div class="phase-dot">6</div><strong>Peer report</strong><span>Findings and recommendations</span></div>
          <div class="phase"><div class="phase-dot">7</div><strong>Committee decision</strong><span>Accreditation outcome</span></div>
        </section>

        <div class="section-head"><div><h2>Self-study and reviewer matrix</h2><p>Applicants organize evidence; reviewers apply the official Yes / Partial / No marking scheme.</p></div><a href="{{ asset('assets/dashboard/gn-central/GN Central') }}/Institutional Accreditation/Current Packet/Application Packet/Self-Study Report_Final.pdf">Open Self-Study Report</a></div>
        <div class="workspace">
          <section class="panel"><div class="panel-head"><h3>Eight Institutional Quality Standards</h3><span>37 criteria · maximum 74 points</span></div><div class="standards" id="standards"></div></section>
          <aside class="side-stack">
            <section class="score-card"><span class="label">Reviewer scoring summary</span><div class="score-main"><strong id="scoreTotal">0</strong><span>of 74 points</span></div><div class="score-track"><i id="scoreBar"></i></div><div class="legend"><div><strong>2</strong><span>YES</span></div><div><strong>1</strong><span>PARTIAL</span></div><div><strong>0</strong><span>NO</span></div></div><p>Scores support the review. They do not automatically determine accreditation; findings, site verification, peer review, and committee judgment remain required.</p></section>
            <section class="panel"><div class="panel-head"><h3>Recent activity</h3><span>Shared timeline</span></div><div class="activity"><div class="activity-list"><div class="activity-item"><i class="activity-dot"></i><div><strong>Self-study opened</strong><p>The institution began organizing its Digital Inventory.</p></div></div><div class="activity-item"><i class="activity-dot"></i><div><strong>Mentor assigned</strong><p>Technical guidance is available during evidence preparation.</p></div></div><div class="activity-item"><i class="activity-dot"></i><div><strong>Application accepted</strong><p>The case moved to Level I: Applicant for Accreditation.</p></div></div></div></div></section>
            <section class="panel reviewer-only"><div class="panel-head"><h3>Reviewer action item</h3><span>Private working note</span></div><div class="action-box"><label for="reviewerNote">Recommendation or follow-up</label><textarea id="reviewerNote" placeholder="Record the evidence gap or next action..."></textarea><button id="saveNote" type="button">Save working note</button></div></section>
          </aside>
        </div>
        <p class="source-note"><strong>Framework source:</strong> <a href="{{ asset('assets/dashboard/gn-central/GN Central') }}/Institutional Accreditation/Current Packet/Application Packet/Self-Study Report_Final.pdf">Self-Study Report</a>, <a href="{{ asset('assets/dashboard/gn-central/GN Central') }}/Institutional Accreditation/Current Packet/Application Packet/IDA_Accreditation_Rating_Matrix (June 2016) w Self-Study Report_Final.xlsx">Rating Matrix</a>, and Institutional Accreditation Plan Version 2.0. Applicant and reviewer changes on this prototype are stored only in the current browser.</p>
      </div>
    </main>
  </div>
  <script>
    const standardData=[
      ['2.1','Institutional Qualifications',[['Government-issued license','Copy of permanent, non-provisional license']]],
      ['2.2','Mission and Planning',[['Three-year Strategic Plan','Copy of Strategic Plan'],['Vision statement','Copy of Vision Statement'],['Mission statement','Copy of Mission Statement'],['Effectiveness measurement tools','Copy of measurement tools'],['Key Performance Indicators','Description of KPIs'],['Shared values and dyslexia definition','Organization or country definition'],['Mission reflected in publications','Brochures, publications, website references']]],
      ['2.3','Organizational and Financial Resources',[['Audited accounts','Past fiscal-year audited statement'],['Financial resources and reserves','Current budget, funding, and reserves'],['Sustainable resources','Evidence of sustainability'],['Policies and procedures','Compliant financial policies and procedures']]],
      ['2.4','Personnel Qualifications',[['Organizational chart','Current organizational chart'],['Employee numbers and roles','Current employee list and titles'],['Credentials and qualifications','Credentials or confirmation letters'],['Client-to-provider ratio','Ratio documentation'],['Job descriptions','Written job descriptions'],['Resumes or CVs','Current personnel qualifications'],['Employee evaluation policies','Evaluation policies and procedures'],['Evaluation tools','Forms used for performance review']]],
      ['2.5','Facilities and Infrastructure',[['Appropriate site and equipment','Photos, floor plan, equipment evidence'],['Safe building and grounds','Local safety documentation'],['Expert safety review','Fire, earthquake, or relevant certificates'],['Current instructional materials','Client materials and publications'],['Maintenance schedule','Facility and technology replacement plan']]],
      ['2.6','Communication and Engagement',[['Internal communication','Examples across departments and staff'],['External communication','Examples with clients, affiliates, and peers']]],
      ['2.7','Impact and Relationships',[['Alliance strategy','Strategy or partnership agreement'],['Strategic alliances','Evidence of joint planning or coordination'],['Joint programs','Promotional materials for affiliated programs']]],
      ['2.8','Self-Evaluation and Development',[['Continuous self-evaluation plan','Copy of institutional plan'],['Outcome data','Evidence of benefits or changes'],['Output data','Measures of programs and activities'],['Service-quality evaluation','Description of evaluation method'],['12-month improvement plan','Planned program, service, or facility improvements'],['Internal and external reviews','Copies of review reports'],['Board or committee minutes','Governance records addressing development']]]
    ];
    const storeKey='ida-accreditation-case-ratings-v1';
    const standards=document.getElementById('standards');
    let ratings=JSON.parse(localStorage.getItem(storeKey)||'{}');
    let role='applicant';
    standardData.forEach(([code,title,criteria],sIndex)=>{
      const details=document.createElement('details'); details.className='standard'; if(sIndex===0) details.open=true;
      details.innerHTML=`<summary><span class="standard-number">${code}</span><span class="standard-title"><strong>${title}</strong><span>${criteria.length} ${criteria.length===1?'criterion':'criteria'}</span></span><span class="meter"><i id="meter-${sIndex}"></i></span><span class="standard-score" id="standard-score-${sIndex}">0/${criteria.length*2}</span></summary><div class="criteria">${criteria.map(([item,evidence],cIndex)=>`<div class="criterion"><p>${item}<small>Evidence: ${evidence}</small></p><select data-key="${sIndex}-${cIndex}" aria-label="Rating for ${item}"><option value="">Not rated</option><option value="2">Yes · 2</option><option value="1">Partial · 1</option><option value="0">No · 0</option></select></div>`).join('')}</div>`;
      standards.appendChild(details);
    });
    function refresh(){
      let total=0,rated=0,max=0; standardData.forEach(([, ,criteria],sIndex)=>{let score=0,standardRated=0;criteria.forEach((_,cIndex)=>{const value=ratings[`${sIndex}-${cIndex}`];if(value!==undefined&&value!==''){score+=Number(value);rated++;standardRated++;}max+=2});document.getElementById(`standard-score-${sIndex}`).textContent=`${score}/${criteria.length*2}`;document.getElementById(`meter-${sIndex}`).style.width=`${standardRated/criteria.length*100}%`;total+=score});
      document.getElementById('scoreTotal').textContent=total;document.getElementById('overallPercent').textContent=`${Math.round(total/max*100)}%`;document.getElementById('scoreBar').style.width=`${total/max*100}%`;document.getElementById('evidenceCount').textContent=`${rated}/37`;
    }
    document.querySelectorAll('.criterion select').forEach(select=>{select.value=ratings[select.dataset.key]??'';select.addEventListener('change',()=>{ratings[select.dataset.key]=select.value;localStorage.setItem(storeKey,JSON.stringify(ratings));refresh()})});
    document.querySelectorAll('[data-role]').forEach(button=>button.addEventListener('click',()=>{role=button.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.criterion select').forEach(x=>x.disabled=role==='applicant');document.querySelectorAll('.reviewer-only').forEach(x=>x.style.display=role==='reviewer'?'block':'none')}));
    document.getElementById('reviewerNote').value=localStorage.getItem('ida-accreditation-reviewer-note')||'';document.getElementById('saveNote').addEventListener('click',event=>{localStorage.setItem('ida-accreditation-reviewer-note',document.getElementById('reviewerNote').value);event.target.textContent='Working note saved ✓';setTimeout(()=>event.target.textContent='Save working note',1400)});
    document.querySelectorAll('.criterion select').forEach(x=>x.disabled=true);document.querySelectorAll('.reviewer-only').forEach(x=>x.style.display='none');refresh();
  </script>
</body>
</html>
