<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Authority Levels & User Profiles | IDA GN Central</title>
  <style>
    :root {
      --navy:#16345b; --navy-dark:#102846; --blue:#2367a6; --teal:#1f9a9c; --gold:#d7a642;
      --ink:#182231; --muted:#647286; --line:#d8e0ea; --soft:#f3f7fa; --white:#fff;
      --good:#287a55; --warn:#946714; --risk:#b54343;
      font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
    }
    *{box-sizing:border-box} body{margin:0;color:var(--ink);background:#eef3f7}.shell{display:grid;grid-template-columns:292px 1fr;min-height:100vh}
    .sidebar{position:sticky;top:0;height:100vh;padding:20px 16px;color:#fff;background:linear-gradient(180deg,var(--navy),var(--navy-dark));overflow:auto}
    .brand{display:flex;align-items:center;gap:12px;padding:4px 8px 20px}.brand img{width:48px;height:48px;object-fit:contain;border-radius:8px;background:#fff}.brand strong,.brand span{display:block}.brand strong{font-size:15px}.brand span{margin-top:3px;color:#c8d7e7;font-size:11px}
    .nav{display:grid;gap:6px}.nav a{display:flex;align-items:center;gap:11px;min-height:42px;padding:10px 12px;border-radius:8px;color:#dce8f3;text-decoration:none;font-size:13px;font-weight:750}.nav a::before{content:attr(data-icon);display:grid;place-items:center;width:23px;height:23px;border-radius:7px;background:rgba(255,255,255,.08)}.nav a:hover,.nav a.active{color:#fff;background:rgba(255,255,255,.12);box-shadow:inset 3px 0 0 var(--gold)}
    .side-note{margin-top:18px;padding:14px;border:1px solid rgba(255,255,255,.13);border-radius:9px;color:#c8d7e7;background:rgba(255,255,255,.06);font-size:11px;line-height:1.55}
    .main{min-width:0}.topbar{min-height:88px;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:18px 28px;border-bottom:1px solid var(--line);background:#fff}.topbar h1{margin:0;color:var(--navy);font-size:24px}.topbar p{margin:5px 0 0;color:var(--muted);font-size:13px}.draft{padding:7px 11px;border:1px solid rgba(215,166,66,.38);border-radius:999px;color:#805a10;background:#fff5dc;font-size:11px;font-weight:850;text-transform:uppercase;letter-spacing:.04em}
    .content{display:grid;gap:18px;padding:24px 28px 38px}.panel{padding:21px;border:1px solid var(--line);border-radius:11px;background:#fff;box-shadow:0 9px 28px rgba(22,52,91,.06)}.panel h2{margin:0;color:var(--navy);font-size:19px}.panel-intro{max-width:880px;margin:7px 0 0;color:var(--muted);font-size:13px;line-height:1.6}
    .notice{display:grid;grid-template-columns:38px 1fr;gap:12px;align-items:start;padding:15px;border:1px solid #cdddea;border-radius:10px;background:linear-gradient(135deg,#edf5fb,#f9fcfe)}.notice-mark{display:grid;place-items:center;width:38px;height:38px;border-radius:10px;color:#fff;background:var(--blue);font-weight:900}.notice strong{display:block;color:var(--navy);font-size:13px}.notice p{margin:4px 0 0;color:#52657a;font-size:12px;line-height:1.5}
    .role-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:17px}.role-card{position:relative;min-height:190px;padding:16px;border:1px solid var(--line);border-radius:10px;background:#fbfdff;overflow:hidden}.role-card::before{content:"";position:absolute;inset:0 auto 0 0;width:4px;background:var(--role-color,var(--blue))}.role-level{color:var(--muted);font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.role-card h3{margin:8px 0 6px;color:var(--navy);font-size:15px}.role-card p{margin:0;color:#596b80;font-size:11px;line-height:1.55}.scope{display:flex;flex-wrap:wrap;gap:5px;margin-top:12px}.scope span{padding:4px 7px;border-radius:999px;color:#38526b;background:#edf3f8;font-size:9.5px;font-weight:750}
    .profiles-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end}.profiles-head label{display:grid;gap:5px;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.05em}.profiles-head select{min-width:230px;padding:9px 32px 9px 10px;border:1px solid #cbd7e3;border-radius:8px;color:var(--navy);background:#fff;font:inherit;font-size:12px;font-weight:750}
    .profile-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:17px}.user-card{display:grid;grid-template-columns:54px 1fr;gap:12px;align-items:start;padding:15px;border:1px solid var(--line);border-radius:10px;background:#fff;transition:.18s ease}.user-card.is-preview{border-color:var(--teal);box-shadow:0 0 0 3px rgba(31,154,156,.12),0 10px 24px rgba(22,52,91,.1)}.avatar{display:grid;place-items:center;width:54px;height:54px;border-radius:14px;color:#fff;background:linear-gradient(145deg,var(--blue),var(--navy));font-size:16px;font-weight:900}.avatar.template{color:var(--navy);background:#e9f0f6}.user-card h3{margin:1px 0 3px;color:var(--navy);font-size:14px}.user-title{display:block;color:#607086;font-size:10.5px;line-height:1.4}.role-pill{display:inline-flex;margin-top:8px;padding:4px 7px;border-radius:999px;color:#0f6f70;background:#e7f7f5;font-size:9px;font-weight:850}.user-status{display:flex;align-items:center;gap:5px;margin-top:7px;color:#68778a;font-size:9.5px}.user-status::before{content:"";width:7px;height:7px;border-radius:50%;background:var(--good)}.profile-actions{grid-column:1/-1;display:flex;gap:7px;margin-top:2px}.profile-actions button{padding:7px 9px;border:1px solid #cbd8e4;border-radius:7px;color:var(--blue);background:#fff;font:inherit;font-size:10px;font-weight:800;cursor:pointer}.profile-actions button:hover{border-color:var(--blue);background:#eff6fb}
    .preview-panel{display:none;margin-top:15px;padding:16px;border:1px solid rgba(31,154,156,.28);border-radius:10px;background:#f1faf8}.preview-panel.open{display:block}.preview-panel h3{margin:0;color:var(--navy);font-size:15px}.preview-meta{margin:5px 0 12px;color:var(--muted);font-size:11px}.preview-columns{display:grid;grid-template-columns:1fr 1fr;gap:16px}.preview-columns h4{margin:0 0 7px;color:#52657a;font-size:10px;text-transform:uppercase;letter-spacing:.06em}.preview-list{display:grid;gap:6px;margin:0;padding:0;list-style:none}.preview-list li{padding:7px 9px;border-radius:7px;color:#38526b;background:#fff;font-size:11px}.preview-list.denied li{color:#855050;background:#fff7f7}
    .matrix-wrap{margin-top:16px;overflow:auto;border:1px solid var(--line);border-radius:10px}table{width:100%;border-collapse:collapse;min-width:1040px}th,td{padding:10px 9px;border-bottom:1px solid #e6ecf2;text-align:center;font-size:10px}th{position:sticky;top:0;color:#fff;background:var(--navy);font-size:9px;text-transform:uppercase;letter-spacing:.04em}th:first-child,td:first-child{text-align:left;position:sticky;left:0;z-index:1}td:first-child{color:var(--navy);background:#fbfdff;font-weight:800;min-width:190px}.yes,.limited,.no{display:inline-flex;align-items:center;justify-content:center;min-width:24px;height:24px;border-radius:7px;font-weight:900}.yes{color:#216947;background:#e7f5ed}.limited{color:#805a10;background:#fff4d8}.no{color:#9a5151;background:#fdeeee}.legend{display:flex;flex-wrap:wrap;gap:12px;margin-top:10px;color:var(--muted);font-size:10px}.legend span{display:flex;align-items:center;gap:5px}
    .controls{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:16px}.control{padding:14px;border:1px solid var(--line);border-radius:9px;background:#fbfdff}.control strong{display:block;color:var(--navy);font-size:12px}.control p{margin:5px 0 0;color:var(--muted);font-size:10.5px;line-height:1.45}
    @@media(max-width:1180px){.role-grid{grid-template-columns:repeat(2,1fr)}.profile-grid{grid-template-columns:repeat(2,1fr)}.controls{grid-template-columns:repeat(2,1fr)}}
    @@media(max-width:900px){.shell{grid-template-columns:1fr}.sidebar{position:static;height:auto}.nav,.side-note{display:none}.content{padding:18px}.topbar{align-items:flex-start;flex-direction:column}.profiles-head{align-items:flex-start;flex-direction:column}.profiles-head select{min-width:min(100%,330px)}.preview-columns{grid-template-columns:1fr}}
    @@media(max-width:620px){.role-grid,.profile-grid,.controls{grid-template-columns:1fr}.content{padding:14px}.panel{padding:16px}}
  </style>
  <link rel="stylesheet" href="{{ asset('assets/dashboard/gn-central/preview-assets') }}/gn-central-navigation.css">
</head>
<body>
  <div class="shell">
    <aside class="sidebar" aria-label="Primary navigation">
      <div class="brand"><img src="{{ asset('assets/dashboard/gn-central/preview-assets') }}/ida-global-network-logo.png" alt="IDA Global Network logo"><div><strong>IDA GN Central</strong><span>Authority administration</span></div></div>
      <nav class="nav">
        <a data-icon="⌂" href="{{ route('dashboard.index') }}">Home</a>
        <a data-icon="▤" href="{{ route('dashboard.membership-applications.index') }}">Applications</a>
        <a data-icon="◎" href="{{ route('dashboard.index') }}#member-panel">Global Network Members</a>
        <a data-icon="♛" data-section="leadership" href="{{ route('dashboard.member-leadership.index') }}">Member Leadership</a>
        <a data-icon="◫" href="{{ route('dashboard.member-operations.index') }}">Member Operations</a>
        <a data-icon="▥" href="{{ route('dashboard.membership-options.index') }}">Resources</a>
        <a data-icon="✪" href="{{ route('dashboard.accreditation.index') }}">Institutional Accreditation</a>
        <a class="active" data-icon="⚙" href="{{ route('dashboard.authority-levels.index') }}">Authority &amp; Profiles</a>
      </nav>
      <div class="side-note">Draft authority model for review. Interface previews do not replace server-side authentication, assigned-case checks or audit controls.</div>
    </aside>

    <main class="main">
      <header class="topbar"><div><h1>Authority Levels &amp; User Profiles</h1><p>Define who can see, manage, review, decide and administer each GN Central area.</p></div><span class="draft">Draft assignments</span></header>
      <div class="content">
        <section class="notice" aria-label="Security implementation note"><div class="notice-mark">i</div><div><strong>Role design is ready; security enforcement belongs in the authenticated system.</strong><p>This page models the approved access structure and user experience. The programmer should enforce every permission on the server as well as in the navigation, following the Lighthouse Central pattern.</p></div></section>

        <section class="panel" aria-labelledby="roles-title">
          <h2 id="roles-title">Eight authority levels</h2><p class="panel-intro">Roles follow the principle of least privilege: users see only the information required for their work, and sensitive actions such as decisions, exports, deletions and permission changes remain separately controlled.</p>
          <div class="role-grid">
            <article class="role-card" style="--role-color:#16345b"><span class="role-level">Level 01</span><h3>System Administrator</h3><p>Technical administration, accounts, roles, security configuration and audit access.</p><div class="scope"><span>Users</span><span>Permissions</span><span>Audit</span><span>Settings</span></div></article>
            <article class="role-card" style="--role-color:#d7a642"><span class="role-level">Level 02</span><h3>Executive Leadership</h3><p>Full programme oversight, aggregated reports, approvals and final membership decisions.</p><div class="scope"><span>All dashboards</span><span>Decide</span><span>Reports</span><span>Export</span></div></article>
            <article class="role-card" style="--role-color:#2367a6"><span class="role-level">Level 03</span><h3>GN Programme Manager</h3><p>Day-to-day administration of members, applications, assignments, content and communications.</p><div class="scope"><span>Manage</span><span>Assign</span><span>Publish</span><span>Export</span></div></article>
            <article class="role-card" style="--role-color:#1f9a9c"><span class="role-level">Level 04</span><h3>Executive Committee Reviewer</h3><p>Reviews committee or assigned membership applications and records recommendations.</p><div class="scope"><span>Assigned review</span><span>Comment</span><span>Recommend</span></div></article>
            <article class="role-card" style="--role-color:#7a58a0"><span class="role-level">Level 05</span><h3>Accreditation Manager</h3><p>Controls accreditation cases, reviewer assignments, stages, evidence and final workflow.</p><div class="scope"><span>All cases</span><span>Assign</span><span>Score</span><span>Manage</span></div></article>
            <article class="role-card" style="--role-color:#4b7f95"><span class="role-level">Level 06</span><h3>Accreditation Reviewer</h3><p>Accesses reviewer training and only the accreditation cases specifically assigned.</p><div class="scope"><span>Assigned cases</span><span>Evidence</span><span>Score</span><span>Comment</span></div></article>
            <article class="role-card" style="--role-color:#287a55"><span class="role-level">Level 07</span><h3>Member Representative</h3><p>Uses member resources and manages only the profile and records belonging to their organization.</p><div class="scope"><span>Own profile</span><span>Own records</span><span>Resources</span><span>Events</span></div></article>
            <article class="role-card" style="--role-color:#8b98a7"><span class="role-level">Level 08</span><h3>Applicant / Public</h3><p>Views approved public guidance and, after verification, accesses only their own application.</p><div class="scope"><span>Public guidance</span><span>Own application</span><span>Readiness</span></div></article>
          </div>
        </section>

        <section class="panel" aria-labelledby="profiles-title">
          <div class="profiles-head"><div><h2 id="profiles-title">Proposed user profiles</h2><p class="panel-intro">Named assignments are based on roles already identified in GN Central and should be confirmed by IDA before activation.</p></div><label>Filter profiles<select id="profileFilter"><option value="all">All profiles</option><option value="leadership">Executive Leadership</option><option value="programme">Programme Management</option><option value="committee">Committee Reviewers</option><option value="accreditation">Accreditation</option><option value="member">Member / Applicant</option><option value="system">System Administration</option></select></label></div>
          <div class="profile-grid" id="profileGrid">
            <article class="user-card" data-group="leadership" data-role="Executive Leadership" data-name="Sonja Banks" data-allowed="Full health dashboard|All membership applications|Programme reports|Final decisions|Aggregated exports" data-denied="Technical security settings|Direct alteration of audit history"><div class="avatar">SB</div><div><h3>Sonja Banks</h3><span class="user-title">IDA Chief Executive Officer</span><span class="role-pill">Executive Leadership</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="leadership" data-role="Executive Leadership" data-name="Mr. Steve O'Brien" data-allowed="Full health dashboard|Committee applications|Programme reports|Final membership decisions|Member directory" data-denied="Technical settings|Accreditation scoring unless assigned"><div class="avatar">SO</div><div><h3>Mr. Steve O'Brien</h3><span class="user-title">Chair, IDA GN Executive Committee</span><span class="role-pill">Executive Leadership</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="leadership" data-role="Executive Leadership" data-name="Dr. Gad Elbeheri" data-allowed="Full health dashboard|Committee applications|Programme reports|Comments and recommendations|Approved exports" data-denied="Technical security settings|Unassigned confidential accreditation evidence"><div class="avatar">GE</div><div><h3>Dr. Gad Elbeheri</h3><span class="user-title">IDA Advisor, Special Projects &amp; Executive Committee</span><span class="role-pill">Executive Leadership</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="programme" data-role="GN Programme Manager" data-name="GN Programme Office" data-allowed="Operational dashboard|All membership applications|Member records|Reviewer assignments|Events and communications|Operational exports" data-denied="System permissions|Sole final decision authority"><div class="avatar template">GN</div><div><h3>GN Programme Office</h3><span class="user-title">Named staff account to be confirmed</span><span class="role-pill">GN Programme Manager</span><span class="user-status">Assignment required</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="accreditation" data-role="Accreditation Manager" data-name="Dana Nwoye" data-allowed="All accreditation cases|Reviewer assignments|Evidence inventory|Process stages|Accreditation reports" data-denied="System-wide user permissions|Unrelated membership decisions"><div class="avatar">DN</div><div><h3>Dana Nwoye</h3><span class="user-title">Manager, Special Projects</span><span class="role-pill">Accreditation Manager</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="committee" data-role="Executive Committee Reviewer" data-name="Dr. Elsa Cárdenas-Hagan" data-allowed="Committee dashboard|Assigned applications|Internal review comments|Recommendations|Member resources" data-denied="Final decision alone|Bulk export|System settings"><div class="avatar">EC</div><div><h3>Dr. Elsa Cárdenas-Hagan</h3><span class="user-title">GN Executive Committee</span><span class="role-pill">Committee Reviewer</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="committee" data-role="Executive Committee Reviewer" data-name="Dr. Eric Tridas" data-allowed="Committee dashboard|Assigned applications|Internal review comments|Recommendations|Member resources" data-denied="Final decision alone|Bulk export|System settings"><div class="avatar">ET</div><div><h3>Dr. Eric Tridas</h3><span class="user-title">GN Executive Committee</span><span class="role-pill">Committee Reviewer</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="committee" data-role="Executive Committee Reviewer" data-name="Professor Charles Haynes" data-allowed="Committee dashboard|Assigned applications|Internal review comments|Recommendations|Member resources" data-denied="Final decision alone|Bulk export|System settings"><div class="avatar">CH</div><div><h3>Professor Charles Haynes</h3><span class="user-title">GN Executive Committee</span><span class="role-pill">Committee Reviewer</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="committee" data-role="Executive Committee Reviewer" data-name="Phyllis Munyi" data-allowed="Committee dashboard|Assigned applications|Internal review comments|Recommendations|Own organization profile" data-denied="Final decision alone|Other member private records|System settings"><div class="avatar">PM</div><div><h3>Phyllis Munyi</h3><span class="user-title">GN Executive Committee; CEO, Kenya Dyslexia Association</span><span class="role-pill">Committee Reviewer</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="committee" data-role="Executive Committee Reviewer" data-name="Dr. Geetha Shantha Ram" data-allowed="Committee dashboard|Assigned applications|Internal review comments|Recommendations|Own organization profile" data-denied="Final decision alone|Other member private records|System settings"><div class="avatar">GS</div><div><h3>Dr. Geetha Shantha Ram</h3><span class="user-title">GN Executive Committee; Dyslexia Association of Singapore</span><span class="role-pill">Committee Reviewer</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="committee" data-role="Executive Committee Reviewer" data-name="Mr. Lee Siang" data-allowed="Committee dashboard|Assigned applications|Internal review comments|Recommendations|Own organization profile" data-denied="Final decision alone|Other member private records|System settings"><div class="avatar">LS</div><div><h3>Mr. Lee Siang</h3><span class="user-title">GN Executive Committee; CEO, Dyslexia Association of Singapore</span><span class="role-pill">Committee Reviewer</span><span class="user-status">Proposed active profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="accreditation" data-role="Accreditation Reviewer" data-name="Assigned Accreditation Reviewer" data-allowed="Reviewer training|Assigned accreditation cases|Assigned evidence|Scoring matrix|Reviewer comments" data-denied="Unassigned cases|Applicant-private internal comments|Final accreditation decision|Bulk export"><div class="avatar template">AR</div><div><h3>Assigned Accreditation Reviewer</h3><span class="user-title">Reusable profile template</span><span class="role-pill">Accreditation Reviewer</span><span class="user-status">Template profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="member" data-role="Member Representative" data-name="Organization Representative" data-allowed="Member dashboard|Public member directory|Own organization profile|Own applications|Own accreditation record|Member resources and events" data-denied="Other organizations' private records|Internal reviewer comments|Programme-wide reports|Decisions"><div class="avatar template">MR</div><div><h3>Organization Representative</h3><span class="user-title">One or more verified contacts per member</span><span class="role-pill">Member Representative</span><span class="user-status">Template profile</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
            <article class="user-card" data-group="system" data-role="System Administrator" data-name="GN System Administrator" data-allowed="User accounts|Roles and permissions|Authentication configuration|Audit logs|Technical settings|All-system support" data-denied="Programme decisions unless separately assigned"><div class="avatar template">SA</div><div><h3>GN System Administrator</h3><span class="user-title">Named technical account to be confirmed</span><span class="role-pill">System Administrator</span><span class="user-status">Assignment required</span></div><div class="profile-actions"><button type="button" class="preview-user">Preview access</button></div></article>
          </div>
          <div class="preview-panel" id="accessPreview" aria-live="polite"><h3 id="previewTitle">Access preview</h3><p class="preview-meta" id="previewMeta"></p><div class="preview-columns"><div><h4>Can access</h4><ul class="preview-list" id="allowedList"></ul></div><div><h4>Restricted</h4><ul class="preview-list denied" id="deniedList"></ul></div></div></div>
        </section>

        <section class="panel" aria-labelledby="matrix-title">
          <h2 id="matrix-title">Section access matrix</h2><p class="panel-intro">A yellow marker means limited, organization-specific or assigned-case access. Final permissions should be stored as individual actions rather than one broad page-level switch.</p>
          <div class="matrix-wrap"><table aria-label="GN Central authority matrix"><thead><tr><th>Section / action</th><th>System Admin</th><th>Executive</th><th>Programme Manager</th><th>Committee Reviewer</th><th>Accreditation Manager</th><th>Accreditation Reviewer</th><th>Member Rep.</th><th>Applicant / Public</th></tr></thead><tbody>
            <tr><td>Programme health dashboard</td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td></tr>
            <tr><td>All membership applications</td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td></tr>
            <tr><td>Assigned / own application</td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="limited">◐</span></td><td><span class="limited">◐</span></td></tr>
            <tr><td>Record final membership decision</td><td><span class="limited">◐</span></td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td></tr>
            <tr><td>Member directory and resources</td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td></tr>
            <tr><td>Edit member profile</td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td><td><span class="yes">✓</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td></tr>
            <tr><td>All accreditation cases</td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="yes">✓</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td></tr>
            <tr><td>Assigned / own accreditation case</td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="limited">◐</span></td><td><span class="limited">◐</span></td></tr>
            <tr><td>Reviewer training and scoring</td><td><span class="limited">◐</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td></tr>
            <tr><td>Reports and exports</td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="yes">✓</span></td><td><span class="no">—</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td><td><span class="limited">◐</span></td><td><span class="no">—</span></td></tr>
            <tr><td>Users, roles and permissions</td><td><span class="yes">✓</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td><td><span class="no">—</span></td></tr>
          </tbody></table></div>
          <div class="legend"><span><b class="yes">✓</b> Full access</span><span><b class="limited">◐</b> Limited, assigned or own-record access</span><span><b class="no">—</b> No access</span></div>
        </section>

        <section class="panel" aria-labelledby="controls-title"><h2 id="controls-title">Required security controls</h2><p class="panel-intro">These controls should be treated as part of the authority model, not optional enhancements.</p><div class="controls">
          <article class="control"><strong>Assigned-case enforcement</strong><p>Reviewers cannot reach unassigned membership or accreditation records by changing a URL.</p></article>
          <article class="control"><strong>Comment visibility</strong><p>Separate internal reviewer notes from comments that applicants and members are allowed to read.</p></article>
          <article class="control"><strong>Decision authority</strong><p>Recommendations and final decisions are distinct permissions, with named decision-makers.</p></article>
          <article class="control"><strong>Export protection</strong><p>Restrict bulk downloads and record who exported which dataset and when.</p></article>
          <article class="control"><strong>Audit trail</strong><p>Log sign-ins, assignments, edits, scores, decisions, exports and permission changes.</p></article>
          <article class="control"><strong>No hard deletion</strong><p>Archive records wherever possible; reserve permanent deletion for the System Administrator.</p></article>
          <article class="control"><strong>Account review</strong><p>Review active accounts and assigned roles at least quarterly and immediately after role changes.</p></article>
          <article class="control"><strong>Server-side authorization</strong><p>Navigation hiding improves usability, but every protected request must also be checked by the backend.</p></article>
        </div></section>
      </div>
    </main>
  </div>
  <script>
    const filter = document.getElementById('profileFilter');
    const cards = [...document.querySelectorAll('.user-card')];
    const preview = document.getElementById('accessPreview');
    const previewTitle = document.getElementById('previewTitle');
    const previewMeta = document.getElementById('previewMeta');
    const allowedList = document.getElementById('allowedList');
    const deniedList = document.getElementById('deniedList');

    filter.addEventListener('change', () => {
      cards.forEach(card => card.hidden = filter.value !== 'all' && card.dataset.group !== filter.value);
    });

    function fillList(element, value) {
      element.innerHTML = '';
      value.split('|').forEach(item => {
        const li = document.createElement('li');
        li.textContent = item;
        element.appendChild(li);
      });
    }

    document.getElementById('profileGrid').addEventListener('click', event => {
      const button = event.target.closest('.preview-user');
      if (!button) return;
      const card = button.closest('.user-card');
      cards.forEach(item => item.classList.toggle('is-preview', item === card));
      previewTitle.textContent = `${card.dataset.name} access preview`;
      previewMeta.textContent = card.dataset.role;
      fillList(allowedList, card.dataset.allowed);
      fillList(deniedList, card.dataset.denied);
      preview.classList.add('open');
      preview.scrollIntoView({behavior:'smooth', block:'nearest'});
    });
  </script>
</body>
</html>
